name: Auto Approve

on:
  pull_request:

jobs:
  approve:
    name: Auto Approve
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.head.repo.full_name == 'keystonejs/keystone' }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          # we want to force the action to compare with git rather than GitHub's API
          token: ''
          filters: |
            shouldRequireApprovalFromPerson:
              - '!{packages-next,examples-next,design-system}/**'
      - uses: Thinkmill/auto-approve-action@v1
        with:
          approve: ${{ steps.filter.outputs.shouldRequireApprovalFromPerson == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
