name: CI - Windows

on:
  workflow_dispatch:

concurrency:
  group: ci-tests-windows-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit_tests:
    name: Package Unit Tests
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@main
      - uses: ./.github/actions/ci-setup

      - name: Unit tests
        run: pnpm jest --ci --runInBand --testPathIgnorePatterns=admin-ui-tests --testPathIgnorePatterns=api-tests --testPathIgnorePatterns=examples-smoke-tests --testPathIgnorePatterns=examples/testing
